2022-04-26 10:50:16,439 INFO    MainThread:2393800 [wandb_setup.py:_flush():75] Loading settings from /home/rishabh/.config/wandb/settings
2022-04-26 10:50:16,439 INFO    MainThread:2393800 [wandb_setup.py:_flush():75] Loading settings from /home/rishabh/practice_runs/cs4243-project/wandb/settings
2022-04-26 10:50:16,439 INFO    MainThread:2393800 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-04-26 10:50:16,439 INFO    MainThread:2393800 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-04-26 10:50:16,439 INFO    MainThread:2393800 [wandb_init.py:_log_setup():437] Logging user logs to /home/rishabh/practice_runs/cs4243-project/wandb/run-20220426_105016-1kunu2q4/logs/debug.log
2022-04-26 10:50:16,439 INFO    MainThread:2393800 [wandb_init.py:_log_setup():438] Logging internal logs to /home/rishabh/practice_runs/cs4243-project/wandb/run-20220426_105016-1kunu2q4/logs/debug-internal.log
2022-04-26 10:50:16,439 INFO    MainThread:2393800 [wandb_init.py:init():471] calling init triggers
2022-04-26 10:50:16,439 INFO    MainThread:2393800 [wandb_init.py:init():475] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.02, 'epochs': 20, 'batch_size': 512}
2022-04-26 10:50:16,439 INFO    MainThread:2393800 [wandb_init.py:init():491] re-initializing run, found existing run on stack: 1of4mu4k
2022-04-26 10:50:16,442 INFO    MainThread:2393800 [wandb_run.py:_finish():1685] finishing run rish-16/cs4243-project/1of4mu4k
2022-04-26 10:50:16,442 INFO    MainThread:2393800 [jupyter.py:save_history():435] not saving jupyter history
2022-04-26 10:50:16,442 INFO    MainThread:2393800 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-04-26 10:50:16,442 INFO    MainThread:2393800 [wandb_init.py:_jupyter_teardown():369] cleaning up jupyter logic
2022-04-26 10:50:16,443 INFO    MainThread:2393800 [wandb_run.py:_atexit_cleanup():1866] got exitcode: 0
2022-04-26 10:50:16,444 INFO    MainThread:2393800 [wandb_run.py:_restore():1838] restore
2022-04-26 10:50:17,133 INFO    MainThread:2393800 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 869
  total_bytes: 869
}

2022-04-26 10:50:17,250 INFO    MainThread:2393800 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 869
  total_bytes: 869
}

2022-04-26 10:50:17,701 INFO    MainThread:2393800 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 869
  total_bytes: 869
}

2022-04-26 10:50:18,481 INFO    MainThread:2393800 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 869
  total_bytes: 10465
}

2022-04-26 10:50:18,585 INFO    MainThread:2393800 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 869
  total_bytes: 10465
}

2022-04-26 10:50:18,688 INFO    MainThread:2393800 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 869
  total_bytes: 10465
}

2022-04-26 10:50:18,790 INFO    MainThread:2393800 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1364
  total_bytes: 10465
}

2022-04-26 10:50:18,894 INFO    MainThread:2393800 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10465
  total_bytes: 10465
}

2022-04-26 10:50:18,998 INFO    MainThread:2393800 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10465
  total_bytes: 10465
}

2022-04-26 10:50:19,100 INFO    MainThread:2393800 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10465
  total_bytes: 10465
}

2022-04-26 10:50:19,203 INFO    MainThread:2393800 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10465
  total_bytes: 10465
}

2022-04-26 10:50:19,305 INFO    MainThread:2393800 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10465
  total_bytes: 10465
}

2022-04-26 10:50:19,408 INFO    MainThread:2393800 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10465
  total_bytes: 10465
}

2022-04-26 10:50:20,145 INFO    MainThread:2393800 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10465
  total_bytes: 10465
}

2022-04-26 10:50:20,728 INFO    MainThread:2393800 [wandb_run.py:_on_finish():1995] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10465
  total_bytes: 10465
}
local_info {
}

2022-04-26 10:50:21,878 INFO    MainThread:2393800 [wandb_run.py:_footer_history_summary_info():3102] rendering history
2022-04-26 10:50:21,878 INFO    MainThread:2393800 [wandb_run.py:_footer_history_summary_info():3134] rendering summary
2022-04-26 10:50:21,881 INFO    MainThread:2393800 [wandb_run.py:_footer_sync_info():3057] logging synced files
2022-04-26 10:50:21,888 INFO    MainThread:2393800 [wandb_init.py:init():524] starting backend
2022-04-26 10:50:21,888 INFO    MainThread:2393800 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-04-26 10:50:21,890 INFO    MainThread:2393800 [backend.py:ensure_launched():217] starting backend process...
2022-04-26 10:50:21,960 INFO    MainThread:2393800 [backend.py:ensure_launched():222] started backend process with pid: 2396238
2022-04-26 10:50:21,962 INFO    MainThread:2393800 [wandb_init.py:init():533] backend started and connected
2022-04-26 10:50:21,978 INFO    MainThread:2393800 [wandb_run.py:_label_probe_notebook():1084] probe notebook
2022-04-26 10:50:21,978 INFO    MainThread:2393800 [wandb_run.py:_label_probe_notebook():1094] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-04-26 10:50:21,978 INFO    MainThread:2393800 [wandb_init.py:init():597] updated telemetry
2022-04-26 10:50:22,137 INFO    MainThread:2393800 [wandb_init.py:init():628] communicating run to backend with 30 second timeout
2022-04-26 10:50:22,921 INFO    MainThread:2393800 [wandb_run.py:_on_init():1923] communicating current version
2022-04-26 10:50:22,982 INFO    MainThread:2393800 [wandb_run.py:_on_init():1927] got version response 
2022-04-26 10:50:22,982 INFO    MainThread:2393800 [wandb_init.py:init():659] starting run threads in backend
2022-04-26 10:50:24,415 INFO    MainThread:2393800 [wandb_run.py:_console_start():1897] atexit reg
2022-04-26 10:50:24,415 INFO    MainThread:2393800 [wandb_run.py:_redirect():1770] redirect: SettingsConsole.WRAP
2022-04-26 10:50:24,415 INFO    MainThread:2393800 [wandb_run.py:_redirect():1807] Wrapping output streams.
2022-04-26 10:50:24,416 INFO    MainThread:2393800 [wandb_run.py:_redirect():1831] Redirects installed.
2022-04-26 10:50:24,417 INFO    MainThread:2393800 [wandb_init.py:init():684] run started, returning control to user process
2022-04-26 10:50:24,516 INFO    MainThread:2393800 [wandb_setup.py:_flush():75] Loading settings from /home/rishabh/.config/wandb/settings
2022-04-26 10:50:24,516 INFO    MainThread:2393800 [wandb_setup.py:_flush():75] Loading settings from /home/rishabh/practice_runs/cs4243-project/wandb/settings
2022-04-26 10:50:24,516 INFO    MainThread:2393800 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-04-26 10:50:24,516 INFO    MainThread:2393800 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-04-26 10:50:24,516 INFO    MainThread:2393800 [wandb_init.py:_log_setup():437] Logging user logs to /home/rishabh/practice_runs/cs4243-project/wandb/run-20220426_105024-1g2fnfs2/logs/debug.log
2022-04-26 10:50:24,516 INFO    MainThread:2393800 [wandb_init.py:_log_setup():438] Logging internal logs to /home/rishabh/practice_runs/cs4243-project/wandb/run-20220426_105024-1g2fnfs2/logs/debug-internal.log
2022-04-26 10:50:24,516 INFO    MainThread:2393800 [wandb_init.py:_jupyter_setup():387] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f623924a390>
2022-04-26 10:50:24,517 INFO    MainThread:2393800 [wandb_init.py:init():471] calling init triggers
2022-04-26 10:50:24,517 INFO    MainThread:2393800 [wandb_init.py:init():475] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.02, 'epochs': 20, 'batch_size': 512}
2022-04-26 10:50:24,517 INFO    MainThread:2393800 [wandb_init.py:init():491] re-initializing run, found existing run on stack: 1kunu2q4
2022-04-26 10:50:24,518 INFO    MainThread:2393800 [wandb_run.py:_finish():1685] finishing run rish-16/cs4243-project/1kunu2q4
2022-04-26 10:50:24,518 INFO    MainThread:2393800 [wandb_run.py:_atexit_cleanup():1866] got exitcode: 0
2022-04-26 10:50:24,519 INFO    MainThread:2393800 [wandb_run.py:_restore():1838] restore
2022-04-26 10:50:24,922 INFO    MainThread:2393800 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 869
  total_bytes: 869
}

2022-04-26 10:50:25,107 INFO    MainThread:2393800 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 869
  total_bytes: 869
}

2022-04-26 10:50:25,385 INFO    MainThread:2393800 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 869
  total_bytes: 869
}

2022-04-26 10:50:25,958 INFO    MainThread:2393800 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 869
  total_bytes: 8782
}

2022-04-26 10:50:26,062 INFO    MainThread:2393800 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 869
  total_bytes: 8782
}

2022-04-26 10:50:26,165 INFO    MainThread:2393800 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 869
  total_bytes: 8782
}

2022-04-26 10:50:26,267 INFO    MainThread:2393800 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8782
  total_bytes: 8782
}

2022-04-26 10:50:26,371 INFO    MainThread:2393800 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8782
  total_bytes: 8782
}

2022-04-26 10:50:26,474 INFO    MainThread:2393800 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8782
  total_bytes: 8782
}

2022-04-26 10:50:26,576 INFO    MainThread:2393800 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8782
  total_bytes: 8782
}

2022-04-26 10:50:26,679 INFO    MainThread:2393800 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8782
  total_bytes: 8782
}

2022-04-26 10:50:26,781 INFO    MainThread:2393800 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8782
  total_bytes: 8782
}

2022-04-26 10:50:27,945 INFO    MainThread:2393800 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8782
  total_bytes: 8782
}

2022-04-26 10:50:28,553 INFO    MainThread:2393800 [wandb_run.py:_on_finish():1995] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8782
  total_bytes: 8782
}
local_info {
}

2022-04-26 10:50:29,752 INFO    MainThread:2393800 [wandb_run.py:_footer_history_summary_info():3102] rendering history
2022-04-26 10:50:29,752 INFO    MainThread:2393800 [wandb_run.py:_footer_history_summary_info():3134] rendering summary
2022-04-26 10:50:29,755 INFO    MainThread:2393800 [wandb_run.py:_footer_sync_info():3057] logging synced files
